//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPARAISAL_TOTAL_POINTS
    {
        public string EMPLOYEE_ID { get; set; }
        public string Month { get; set; }
        public string YEAR { get; set; }
        public Nullable<decimal> Total_Points { get; set; }
        public Nullable<decimal> Grand_Total_Points { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> IS_PROCESSED { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
