//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPRAISAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPRAISAL()
        {
            this.APPRAISAL_POINTS = new HashSet<APPRAISAL_POINTS>();
        }
    
        public int APPRAISAL_ID { get; set; }
        public string APPRAISAL_DESC { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public Nullable<bool> IS_TEACHER { get; set; }
        public Nullable<bool> IS_HEAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPRAISAL_POINTS> APPRAISAL_POINTS { get; set; }
    }
}
