//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPRAISAL_POINTS
    {
        public int APPRAISAL_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string YEAR { get; set; }
        public Nullable<decimal> JAN { get; set; }
        public Nullable<decimal> FEB { get; set; }
        public Nullable<decimal> MAR { get; set; }
        public Nullable<decimal> APR { get; set; }
        public Nullable<decimal> MAY { get; set; }
        public Nullable<decimal> JUN { get; set; }
        public Nullable<decimal> JUL { get; set; }
        public Nullable<decimal> AUG { get; set; }
        public Nullable<decimal> SEP { get; set; }
        public Nullable<decimal> OCT { get; set; }
        public Nullable<decimal> NOV { get; set; }
        public Nullable<decimal> DEC { get; set; }
        public string Jan_Achievements { get; set; }
        public string Jan_Suggestion { get; set; }
        public string Feb_Achievements { get; set; }
        public string Feb_Suggestion { get; set; }
        public string Mar_Achievements { get; set; }
        public string Mar_Suggestion { get; set; }
        public string Apr_Achievements { get; set; }
        public string Apr_Suggestion { get; set; }
        public string May_Achievements { get; set; }
        public string May_Suggestion { get; set; }
        public string Jun_Achievements { get; set; }
        public string Jun_Suggestion { get; set; }
        public string Jul_Achievements { get; set; }
        public string Jul_Suggestion { get; set; }
        public string Aug_Achievements { get; set; }
        public string Aug_Suggestion { get; set; }
        public string Sep_Achievements { get; set; }
        public string Sep_Suggestion { get; set; }
        public string Oct_Achievements { get; set; }
        public string Oct_Suggestion { get; set; }
        public string Nov_Achievements { get; set; }
        public string Nove_Suggestion { get; set; }
        public string Dec_Achievements { get; set; }
        public string Dec_Suggestion { get; set; }
    
        public virtual APPRAISAL APPRAISAL { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
