//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_LOG
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DateTime { get; set; }
        public string DEVICE_NAME { get; set; }
        public string MODULE { get; set; }
        public string ACTION { get; set; }
        public string USERID { get; set; }
        public string PROFESSION { get; set; }
        public string DECRIPTION { get; set; }
    }
}
