//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCE
    {
        public string EMPLOYEE_ID { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DETAIL { get; set; }
        public Nullable<decimal> INCOME { get; set; }
        public Nullable<decimal> EXPENSE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
