//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_USER
    {
        public int GROUP_ID { get; set; }
        public int TEACHER_STUDENT_ID { get; set; }
    
        public virtual GROUP GROUP { get; set; }
    }
}
