//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Managed
    {
        public string EMPLOYEE_ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> OnTime_Apr_ { get; set; }
        public Nullable<decimal> Late_Apr_ { get; set; }
        public Nullable<decimal> Absent_Apr_ { get; set; }
        public Nullable<decimal> OnTime_May_ { get; set; }
        public Nullable<decimal> Late_May_ { get; set; }
        public Nullable<decimal> Absent_May_ { get; set; }
        public Nullable<decimal> OnTime_Jun_ { get; set; }
        public Nullable<decimal> Late_Jun_ { get; set; }
        public Nullable<decimal> Absent_Jun_ { get; set; }
        public Nullable<decimal> OnTime_Jul_ { get; set; }
        public Nullable<decimal> Late_Jul_ { get; set; }
        public Nullable<decimal> Absent_Jul_ { get; set; }
        public Nullable<decimal> OnTime_Aug_ { get; set; }
        public Nullable<decimal> Late_Aug_ { get; set; }
        public Nullable<decimal> Absent_Aug_ { get; set; }
        public Nullable<decimal> OnTime_Sep_ { get; set; }
        public Nullable<decimal> Late_Sep_ { get; set; }
        public Nullable<decimal> Absent_Sep_ { get; set; }
        public Nullable<decimal> OnTime_Oct_ { get; set; }
        public Nullable<decimal> Late_Oct_ { get; set; }
        public Nullable<decimal> Absent_Oct_ { get; set; }
        public Nullable<decimal> OnTime_Nov_ { get; set; }
        public Nullable<decimal> Late_Nov_ { get; set; }
        public Nullable<decimal> Absent_Nov_ { get; set; }
        public Nullable<decimal> OnTime_Dec_ { get; set; }
        public Nullable<decimal> Late_Dec_ { get; set; }
        public Nullable<decimal> Absent_Dec_ { get; set; }
        public Nullable<decimal> OnTime_Jan_ { get; set; }
        public Nullable<decimal> Late_Jan_ { get; set; }
        public Nullable<decimal> Absent_Jan_ { get; set; }
        public Nullable<decimal> OnTime_Feb_ { get; set; }
        public Nullable<decimal> Late_Feb_ { get; set; }
        public Nullable<decimal> Absent_Feb_ { get; set; }
        public Nullable<decimal> OnTime_Mar_ { get; set; }
        public Nullable<decimal> Late_Mar_ { get; set; }
        public Nullable<decimal> Absent_Mar_ { get; set; }
        public Nullable<decimal> OnTime_Tot_ { get; set; }
        public Nullable<decimal> Late_Tot_ { get; set; }
        public Nullable<decimal> Absent_Tot_ { get; set; }
        public Nullable<decimal> Absent_Scaled_ { get; set; }
        public Nullable<decimal> Remaining_Leaves { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
