//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_1
    {
        public string Employee_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Day { get; set; }
        public System.TimeSpan TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public string Status { get; set; }
    }
}
