//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KI_MANAGEMENT_SYSTEMEntities : DbContext
    {
        public KI_MANAGEMENT_SYSTEMEntities()
            : base("name=KI_MANAGEMENT_SYSTEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPARAISAL_TOTAL_POINTS> APPARAISAL_TOTAL_POINTS { get; set; }
        public virtual DbSet<APPRAISAL> APPRAISALs { get; set; }
        public virtual DbSet<APPRAISAL_POINTS> APPRAISAL_POINTS { get; set; }
        public virtual DbSet<CLASS> CLASSES { get; set; }
        public virtual DbSet<COURS> COURSES { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<DESIGNATION> DESIGNATIONs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<HRM> HRMS { get; set; }
        public virtual DbSet<HRMS_1> HRMS_1 { get; set; }
        public virtual DbSet<PAY_SLIP> PAY_SLIP { get; set; }
        public virtual DbSet<PAY_SLIP_DETAILS> PAY_SLIP_DETAILS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<RECEIPT_DETAILS> RECEIPT_DETAILS { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Report_Filter> Report_Filter { get; set; }
        public virtual DbSet<Report_Filter_Mapping> Report_Filter_Mapping { get; set; }
        public virtual DbSet<SALARY> SALARies { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<STUDENT_PROGRESS> STUDENT_PROGRESS { get; set; }
        public virtual DbSet<STUDENT_STATUS> STUDENT_STATUS { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTS { get; set; }
        public virtual DbSet<TEST_RESULT> TEST_RESULT { get; set; }
        public virtual DbSet<YEAR> YEARs { get; set; }
        public virtual DbSet<AUDIT_LOG> AUDIT_LOG { get; set; }
        public virtual DbSet<FINANCE> FINANCEs { get; set; }
        public virtual DbSet<GROUP_USER> GROUP_USER { get; set; }
        public virtual DbSet<LOGIN_AUDIT> LOGIN_AUDIT { get; set; }
        public virtual DbSet<STUDENT_FEE> STUDENT_FEE { get; set; }
        public virtual DbSet<TEST_CIT> TEST_CIT { get; set; }
        public virtual DbSet<TEST_ENGLISH_LANGUAGE> TEST_ENGLISH_LANGUAGE { get; set; }
        public virtual DbSet<TEST_GRAPHICS> TEST_GRAPHICS { get; set; }
        public virtual DbSet<TEST_OFFICE_AUTO> TEST_OFFICE_AUTO { get; set; }
        public virtual DbSet<TEST_RESULT_DETAILS> TEST_RESULT_DETAILS { get; set; }
        public virtual DbSet<HRMS_EMPLOYEE> HRMS_EMPLOYEE { get; set; }
        public virtual DbSet<HRMS_Managed> HRMS_Managed { get; set; }
        public virtual DbSet<APPLICATION_CONFIGURATION> APPLICATION_CONFIGURATION { get; set; }
        public virtual DbSet<Import> Imports { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATIONS { get; set; }
    }
}
