//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_AUDIT
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string DateTime { get; set; }
        public string DEVICE_NAME { get; set; }
    }
}
