//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY_SLIP
    {
        public string PAY_SLIP_ID { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string MOD_OF_SALARY { get; set; }
        public string DEPT { get; set; }
        public string DESIGNATION { get; set; }
        public string GRADE { get; set; }
        public Nullable<int> LATE_DAYS { get; set; }
        public Nullable<int> LATE_DEDUCTION_DAYS { get; set; }
        public Nullable<int> ABSENT_DAYS { get; set; }
        public Nullable<decimal> TOTAL_EARNING { get; set; }
        public Nullable<decimal> TOTAL_DEDUCTION { get; set; }
        public Nullable<decimal> NET_PAY { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PAY_SLIP_DETAILS PAY_SLIP_DETAILS { get; set; }
    }
}
