//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAY_SLIP_DETAILS
    {
        public string PAY_SLIP_ID { get; set; }
        public string CLASS { get; set; }
        public Nullable<int> WORKING_DAYS { get; set; }
        public Nullable<decimal> PER_STUDENT_SALARY { get; set; }
        public Nullable<int> NO_OF_STUDENTS { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT_PER_CLASS { get; set; }
        public Nullable<decimal> AMOUNT_PER_DAY { get; set; }
        public Nullable<int> ABSENT_DAYS_DED { get; set; }
        public Nullable<decimal> AMOUNT_DED_LEAVE { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
    
        public virtual PAY_SLIP PAY_SLIP { get; set; }
    }
}
