//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAILS
    {
        public int RECEIPT_NO { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> STUDENT_ID { get; set; }
        public string Name { get; set; }
        public string Month { get; set; }
        public string UnpaidMonths { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
