//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Filter_Mapping
    {
        public int Report_ID { get; set; }
        public int Filter_ID { get; set; }
        public int Pos_X { get; set; }
        public int Pos_Y { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual Report_Filter Report_Filter { get; set; }
    }
}
