//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PROGRESS
    {
        public int STUDENT_ID { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string TASK { get; set; }
        public string DETAILS { get; set; }
        public Nullable<System.DateTime> TASK_DATE { get; set; }
        public Nullable<int> SUBJECT_ID { get; set; }
        public Nullable<decimal> TOTAL_MARKS { get; set; }
        public Nullable<decimal> OBT_MARKS { get; set; }
        public string TEACHER_ID { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
