//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_FEE
    {
        public int STUDENT_ID { get; set; }
        public int YEAR { get; set; }
        public string MONTHS { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<int> SLIP_NO { get; set; }
        public Nullable<System.DateTime> FEE_DATE { get; set; }
    }
}
