//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.STUDENT_PROGRESS = new HashSet<STUDENT_PROGRESS>();
        }
    
        public int STUDENT_ID { get; set; }
        public string NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PHONE { get; set; }
        public string FATHER_PHONE { get; set; }
        public string CNIC { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string GENDER { get; set; }
        public int DEPT_ID { get; set; }
        public int CLASS_ID { get; set; }
        public string SECTION { get; set; }
        public string GROUPS { get; set; }
        public string YEAR { get; set; }
        public string STATUS_ID { get; set; }
        public string SUBJECT { get; set; }
        public Nullable<decimal> TUITION_FEE { get; set; }
        public Nullable<decimal> ADMISSION_FEE { get; set; }
        public Nullable<System.DateTime> ADMISSION_DATE { get; set; }
        public string TIMING { get; set; }
        public string PAYMENT_PLAN { get; set; }
        public string CERTIFICTATE { get; set; }
        public string ImageURL { get; set; }
        public byte[] PIC { get; set; }
        public Nullable<bool> IS_SELECTED { get; set; }
        public string PWD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PROGRESS> STUDENT_PROGRESS { get; set; }
    }
}
