//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_ENGLISH_LANGUAGE
    {
        public int ID { get; set; }
        public string QUESTION { get; set; }
        public string OPTION_A { get; set; }
        public string OPTION_B { get; set; }
        public string OPTION_C { get; set; }
        public string OPTION_D { get; set; }
        public string OPTION_E { get; set; }
        public string ANSWER { get; set; }
    }
}
