//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_FEE
    {
        public int Student_ID { get; set; }
        public int year { get; set; }
        public string Jan { get; set; }
        public string Slip_NoJan { get; set; }
        public string Fee_DateJan { get; set; }
        public string Feb { get; set; }
        public string Slip_NoFeb { get; set; }
        public string Fee_DateFeb { get; set; }
        public string Mar { get; set; }
        public string Slip_NoMar { get; set; }
        public string Fee_DateMar { get; set; }
        public string Apr { get; set; }
        public string Slip_NoApr { get; set; }
        public string Fee_DateApr { get; set; }
        public string May { get; set; }
        public string Slip_NoMay { get; set; }
        public string Fee_DateMay { get; set; }
        public string Jun { get; set; }
        public string Slip_NoJun { get; set; }
        public string Fee_DateJun { get; set; }
        public string Jul { get; set; }
        public string Slip_NoJul { get; set; }
        public string Fee_DateJul { get; set; }
        public string Aug { get; set; }
        public string Slip_NoAug { get; set; }
        public string Fee_DateAug { get; set; }
        public string Sep { get; set; }
        public string Slip_NoSep { get; set; }
        public string Fee_DateSep { get; set; }
        public string Oct { get; set; }
        public string Slip_NoOct { get; set; }
        public string Fee_DateOct { get; set; }
        public string Nov { get; set; }
        public string Slip_NoNov { get; set; }
        public string Fee_DateNov { get; set; }
        public string Dec { get; set; }
        public string Slip_NoDec { get; set; }
        public string Fee_DateDec { get; set; }
    }
}
