//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiMang
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Student_FEE_Copy
    {
        public int student_id { get; set; }
        public int year { get; set; }
        public string MONTHs { get; set; }
        public string FEE { get; set; }
        public string Slip_No { get; set; }
        public string Fee_Date { get; set; }
    }
}
